services:
  # Frontend service
  # frontend:

  # Backend service
  # backend:

  # Database service
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos    # Create todos database at init time
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    # Add health check to ensure PostgreSQL is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
